*"* use this source file for any type of declarations (class
*"* definitions, interfaces or type declarations) you need for
*"* components in the private section

* ===========================================================================
* TYPES
* ===========================================================================

TYPES: BEGIN OF ty_filter,

         " Filtro a nivel de cabeçalho

         acckey                  TYPE RANGE OF zc_tm_cockpit_new-acckey,
         doctype                 TYPE RANGE OF zc_tm_cockpit_new-doctype,
         codstatus               TYPE RANGE OF zc_tm_cockpit_new-codstatus,
         codstatus_txt           TYPE RANGE OF zc_tm_cockpit_new-codstatus_txt,
         bukrs                   TYPE RANGE OF zc_tm_cockpit_new-bukrs,
         bukrs_txt               TYPE RANGE OF zc_tm_cockpit_new-bukrs_txt,
         werks                   TYPE RANGE OF zc_tm_cockpit_new-werks,
         werks_txt               TYPE RANGE OF zc_tm_cockpit_new-werks_txt,
         branch                  TYPE RANGE OF zc_tm_cockpit_new-branch,
         branch_txt              TYPE RANGE OF zc_tm_cockpit_new-branch_txt,
         credat                  TYPE RANGE OF zc_tm_cockpit_new-credat,
         cretim                  TYPE RANGE OF zc_tm_cockpit_new-cretim,
         cenario                 TYPE RANGE OF zc_tm_cockpit_new-cenario,
         cenario_txt             TYPE RANGE OF zc_tm_cockpit_new-cenario_txt,
         lblni                   TYPE RANGE OF zc_tm_cockpit_new-lblni,
         belnr                   TYPE RANGE OF zc_tm_cockpit_new-belnr,
         gjahr                   TYPE RANGE OF zc_tm_cockpit_new-gjahr,
         SupplierInvoice         TYPE RANGE OF zc_tm_cockpit_new-SupplierInvoice,
         FiscalYear              TYPE RANGE OF zc_tm_cockpit_new-FiscalYear,
         BR_NotaFiscal           TYPE RANGE OF zc_tm_cockpit_new-BR_NotaFiscal,
         Driver                  TYPE RANGE OF zc_tm_cockpit_new-Driver,
         DriverName              TYPE RANGE OF zc_tm_cockpit_new-DriverName,
         emit_cnpj_cpf           TYPE RANGE OF zc_tm_cockpit_new-emit_cnpj_cpf,
         emit_ie                 TYPE RANGE OF zc_tm_cockpit_new-emit_ie,
         emit_uf                 TYPE RANGE OF zc_tm_cockpit_new-emit_uf,
         emit_uf_txt             TYPE RANGE OF zc_tm_cockpit_new-emit_uf_txt,
         emit_mun                TYPE RANGE OF zc_tm_cockpit_new-emit_mun,
         Buyer                   TYPE RANGE OF zc_tm_cockpit_new-Buyer,
         BuyerName               TYPE RANGE OF zc_tm_cockpit_new-BuyerName,
         tom_cnpj_cpf            TYPE RANGE OF zc_tm_cockpit_new-tom_cnpj_cpf,
         tom_ie                  TYPE RANGE OF zc_tm_cockpit_new-tom_ie,
         tom_uf                  TYPE RANGE OF zc_tm_cockpit_new-tom_uf,
         tom_uf_txt              TYPE RANGE OF zc_tm_cockpit_new-tom_uf_txt,
         tom_mun                 TYPE RANGE OF zc_tm_cockpit_new-tom_mun,
         Sender                  TYPE RANGE OF zc_tm_cockpit_new-Sender,
         SenderName              TYPE RANGE OF zc_tm_cockpit_new-SenderName,
         rem_cnpj_cpf            TYPE RANGE OF zc_tm_cockpit_new-rem_cnpj_cpf,
         rem_ie                  TYPE RANGE OF zc_tm_cockpit_new-rem_ie,
         rem_uf                  TYPE RANGE OF zc_tm_cockpit_new-rem_uf,
         rem_uf_txt              TYPE RANGE OF zc_tm_cockpit_new-rem_uf_txt,
         rem_mun                 TYPE RANGE OF zc_tm_cockpit_new-rem_mun,
         Consignee               TYPE RANGE OF zc_tm_cockpit_new-Consignee,
         ConsigneeName           TYPE RANGE OF zc_tm_cockpit_new-ConsigneeName,
         dest_cnpj_cpf           TYPE RANGE OF zc_tm_cockpit_new-dest_cnpj_cpf,
         dest_ie                 TYPE RANGE OF zc_tm_cockpit_new-dest_ie,
         dest_uf                 TYPE RANGE OF zc_tm_cockpit_new-dest_uf,
         dest_uf_txt             TYPE RANGE OF zc_tm_cockpit_new-dest_uf_txt,
         dest_mun                TYPE RANGE OF zc_tm_cockpit_new-dest_mun,
         Receiver                TYPE RANGE OF zc_tm_cockpit_new-Receiver,
         ReceiverName            TYPE RANGE OF zc_tm_cockpit_new-ReceiverName,
         receb_cnpj_cpf          TYPE RANGE OF zc_tm_cockpit_new-receb_cnpj_cpf,
         receb_ie                TYPE RANGE OF zc_tm_cockpit_new-receb_ie,
         receb_uf                TYPE RANGE OF zc_tm_cockpit_new-receb_uf,
         receb_uf_txt            TYPE RANGE OF zc_tm_cockpit_new-receb_uf_txt,
         receb_mun               TYPE RANGE OF zc_tm_cockpit_new-receb_mun,
         Shipper                 TYPE RANGE OF zc_tm_cockpit_new-Shipper,
         ShipperName             TYPE RANGE OF zc_tm_cockpit_new-ShipperName,
         exped_cnpj_cpf          TYPE RANGE OF zc_tm_cockpit_new-exped_cnpj_cpf,
         exped_ie                TYPE RANGE OF zc_tm_cockpit_new-exped_ie,
         exped_uf                TYPE RANGE OF zc_tm_cockpit_new-exped_uf,
         exped_uf_txt            TYPE RANGE OF zc_tm_cockpit_new-exped_uf_txt,
         exped_mun               TYPE RANGE OF zc_tm_cockpit_new-exped_mun,
         nfnum9                  TYPE RANGE OF zc_tm_cockpit_new-nfnum9,
         not_code                TYPE RANGE OF zc_tm_cockpit_new-not_code,
         not_code_txt            TYPE RANGE OF zc_tm_cockpit_new-not_code_txt,
         cfop                    TYPE RANGE OF zc_tm_cockpit_new-cfop,
         cfop_ok                 TYPE RANGE OF zc_tm_cockpit_new-cfop_ok,
         sitdoc                  TYPE RANGE OF zc_tm_cockpit_new-sitdoc,
         sitdoc_txt              TYPE RANGE OF zc_tm_cockpit_new-sitdoc_txt,
         dtemi                   TYPE RANGE OF zc_tm_cockpit_new-dtemi,
         hremi                   TYPE RANGE OF zc_tm_cockpit_new-hremi,
         chadat                  TYPE RANGE OF zc_tm_cockpit_new-chadat,
         chatim                  TYPE RANGE OF zc_tm_cockpit_new-chatim,
         usr_lib                 TYPE RANGE OF zc_tm_cockpit_new-usr_lib,
         usnam                   TYPE RANGE OF zc_tm_cockpit_new-usnam,
         usnam_txt               TYPE RANGE OF zc_tm_cockpit_new-usnam_txt,
         tpdoc                   TYPE RANGE OF zc_tm_cockpit_new-tpdoc,
         tpdoc_txt               TYPE RANGE OF zc_tm_cockpit_new-tpdoc_txt,
         possui_anexo_gnre       TYPE RANGE OF zc_tm_cockpit_new-possui_anexo_gnre,
         possui_comprovante_gnre TYPE RANGE OF zc_tm_cockpit_new-possui_comprovante_gnre,
         possui_anexo_nfs        TYPE RANGE OF zc_tm_cockpit_new-possui_anexo_nfs,
         num_fatura              TYPE RANGE OF zc_tm_cockpit_new-num_fatura,
         vct_gko                 TYPE RANGE OF zc_tm_cockpit_new-vct_gko,
         vct_forn                TYPE RANGE OF zc_tm_cockpit_new-vct_forn,
         vct_liq                 TYPE RANGE OF zc_tm_cockpit_new-vct_liq,
         counter                 TYPE RANGE OF zc_tm_cockpit_new-counter,
         pago                    TYPE RANGE OF zc_tm_cockpit_new-pago,
         direct                  TYPE RANGE OF zc_tm_cockpit_new-direct,
         direct_txt              TYPE RANGE OF zc_tm_cockpit_new-direct_txt,
         model                   TYPE RANGE OF zc_tm_cockpit_new-model,
         model_txt               TYPE RANGE OF zc_tm_cockpit_new-model_txt,
         prod_acabado            TYPE RANGE OF zc_tm_cockpit_new-prod_acabado,
         prod_acabado_desc       TYPE RANGE OF zc_tm_cockpit_new-prod_acabado_desc,
         rateio                  TYPE RANGE OF zc_tm_cockpit_new-rateio,
         rateio_txt              TYPE RANGE OF zc_tm_cockpit_new-rateio_txt,
         codevento               TYPE RANGE OF zc_tm_cockpit_new-codevento,
         codevento_txt           TYPE RANGE OF zc_tm_cockpit_new-codevento_txt,
         dhregevento             TYPE RANGE OF zc_tm_cockpit_new-dhregevento,
         tpevento                TYPE RANGE OF zc_tm_cockpit_new-tpevento,
         tpcte                   TYPE RANGE OF zc_tm_cockpit_new-tpcte,
         tpcte_txt               TYPE RANGE OF zc_tm_cockpit_new-tpcte_txt,
         cstat                   TYPE RANGE OF zc_tm_cockpit_new-cstat,
         xmotivo                 TYPE RANGE OF zc_tm_cockpit_new-xmotivo,
         vtprest                 TYPE RANGE OF zc_tm_cockpit_new-vtprest,
         vrec                    TYPE RANGE OF zc_tm_cockpit_new-vrec,
         vbcicms                 TYPE RANGE OF zc_tm_cockpit_new-vbcicms,
         vbciss                  TYPE RANGE OF zc_tm_cockpit_new-vbciss,
         picms                   TYPE RANGE OF zc_tm_cockpit_new-picms,
         piss                    TYPE RANGE OF zc_tm_cockpit_new-piss,
         vicms                   TYPE RANGE OF zc_tm_cockpit_new-vicms,
         viss                    TYPE RANGE OF zc_tm_cockpit_new-viss,
         vcarga                  TYPE RANGE OF zc_tm_cockpit_new-vcarga,
         qcarga                  TYPE RANGE OF zc_tm_cockpit_new-qcarga,
         series                  TYPE RANGE OF zc_tm_cockpit_new-series,
         funrural                TYPE RANGE OF zc_tm_cockpit_new-funrural,
         iss                     TYPE RANGE OF zc_tm_cockpit_new-iss,
         iss_curr                TYPE RANGE OF zc_tm_cockpit_new-iss_curr,
         inss                    TYPE RANGE OF zc_tm_cockpit_new-inss,
         inss_curr               TYPE RANGE OF zc_tm_cockpit_new-inss_curr,
         trio                    TYPE RANGE OF zc_tm_cockpit_new-trio,
         trio_curr               TYPE RANGE OF zc_tm_cockpit_new-trio_curr,
         irrf                    TYPE RANGE OF zc_tm_cockpit_new-irrf,
         irrf_curr               TYPE RANGE OF zc_tm_cockpit_new-irrf_curr,
         moeda                   TYPE RANGE OF zc_tm_cockpit_new-moeda,
         vstel                   TYPE RANGE OF zc_tm_cockpit_new-vstel,
         vstel_txt               TYPE RANGE OF zc_tm_cockpit_new-vstel_txt,
         frete_calculado_gko     TYPE RANGE OF zc_tm_cockpit_new-frete_calculado_gko,
         FreightOrder            TYPE RANGE OF zc_tm_cockpit_new-FreightOrder,
         sfir_id                 TYPE RANGE OF zc_tm_cockpit_new-sfir_id,
         lifecycle               TYPE RANGE OF zc_tm_cockpit_new-lifecycle,
         lifecycle_txt           TYPE RANGE OF zc_tm_cockpit_new-lifecycle_txt,
         confirmation            TYPE RANGE OF zc_tm_cockpit_new-confirmation,
         confirmation_txt        TYPE RANGE OF zc_tm_cockpit_new-confirmation_txt,
         btd_id                  TYPE RANGE OF zc_tm_cockpit_new-btd_id,
*         wbeln                        TYPE RANGE OF zc_tm_cockpit_new-wbeln,
         belnr_fin               TYPE RANGE OF zc_tm_cockpit_new-belnr_fin,
         sakto                   TYPE RANGE OF zc_tm_cockpit_new-sakto,
         sakto_txt               TYPE RANGE OF zc_tm_cockpit_new-sakto_txt,
         kostl                   TYPE RANGE OF zc_tm_cockpit_new-kostl,
         kostl_txt               TYPE RANGE OF zc_tm_cockpit_new-kostl_txt,
         rbkp_budat              TYPE RANGE OF zc_tm_cockpit_new-rbkp_budat,
         cputm                   TYPE RANGE OF zc_tm_cockpit_new-cputm,
         bukrs_doc               TYPE RANGE OF zc_tm_cockpit_new-bukrs_doc,
         bukrs_doc_txt           TYPE RANGE OF zc_tm_cockpit_new-bukrs_doc_txt,
         budat                   TYPE RANGE OF zc_tm_cockpit_new-budat,
         augdt                   TYPE RANGE OF zc_tm_cockpit_new-augdt,
         crenam                  TYPE RANGE OF zc_tm_cockpit_new-crenam,
         crenam_txt              TYPE RANGE OF zc_tm_cockpit_new-crenam_txt,
         chanam                  TYPE RANGE OF zc_tm_cockpit_new-chanam,
         chanam_txt              TYPE RANGE OF zc_tm_cockpit_new-chanam_txt,
         desconto                TYPE RANGE OF zc_tm_cockpit_new-desconto,
         pis                     TYPE RANGE OF zc_tm_cockpit_new-pis,
         cofins                  TYPE RANGE OF zc_tm_cockpit_new-cofins,
         frete_cotado_fluig      TYPE RANGE OF zc_tm_cockpit_new-frete_cotado_fluig,
         gro_wei_val             TYPE RANGE OF zc_tm_cockpit_new-gro_wei_val,
         gro_wei_uni             TYPE RANGE OF zc_tm_cockpit_new-gro_wei_uni,
         autenticacao_bancaria   TYPE RANGE OF zc_tm_cockpit_new-autenticacao_bancaria,
         SuplrFrtInvcReqUUID     TYPE RANGE OF zc_tm_cockpit_new-SuplrFrtInvcReqUUID,
         PurchaseOrder           TYPE RANGE OF zc_tm_cockpit_new-PurchaseOrder,
         TransportationOrderUUID TYPE RANGE OF zc_tm_cockpit_new-TransportationOrderUUID,
         UltimoLog               TYPE RANGE OF zc_tm_cockpit_new-UltimoLog,
         motivoRejeicao          TYPE RANGE OF zc_tm_cockpit_new-motivoRejeicao,
         estornoAgrupamento      TYPE RANGE OF zc_tm_cockpit_new-estornoAgrupamento,
         estornoMiro             TYPE RANGE OF zc_tm_cockpit_new-estornoMiro,
         estornoPedido           TYPE RANGE OF zc_tm_cockpit_new-estornoPedido,

         " Filtro a nivel de item

         docnum_ref              TYPE RANGE OF zc_tm_cockpit_new-docnum_ref,

       END OF ty_filter.

* ===========================================================================
* CONSTANTS
* ===========================================================================

CONSTANTS:

  BEGIN OF gc_cds,
    cockpit TYPE string VALUE 'COCKPIT',              " Cockpit
  END OF gc_cds.
