@AbapCatalog.sqlViewName: 'ZITMRCST'
@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Interface final Custos Entrega Devolução'
@VDM.viewType: #COMPOSITE
define view ZI_TM_CUSTOS_ENTREGA
  as select from    ZI_TM_REL_CUSTOS_ENTREGA_DEV as _RelCustosEntrega
    left outer join t179t                        as _FamiliaProdutoNivel1 on _RelCustosEntrega.ProductHierarchy5 = _FamiliaProdutoNivel1.prodh
    left outer join t179t                        as _FamiliaProdutoNivel2 on _RelCustosEntrega.ProductHierarchy10 = _FamiliaProdutoNivel2.prodh
    left outer join t179t                        as _FamiliaProdutoNivel3 on _RelCustosEntrega.ProductHierarchy = _FamiliaProdutoNivel3.prodh

  association [0..1] to ZI_TM_VH_UG as _UGOrigem  on _UGOrigem.LocationId = $projection.UGOrigem
  association [0..1] to ZI_TM_VH_UG as _UGDestino on _UGDestino.LocationId = $projection.UGDestino
{
  key _RelCustosEntrega.OrdemId,
      _RelCustosEntrega.OrdemFreteNum,
      _RelCustosEntrega.DataCriacaoOF,
      _RelCustosEntrega.CriadoPorOF,
      _RelCustosEntrega.Placa,
      _RelCustosEntrega.GrupoVeiculo,
      _RelCustosEntrega.TipoVeiculo,
      _RelCustosEntrega.DocNum,
      _RelCustosEntrega.NotaFiscalNum,
      _RelCustosEntrega.DataEmissaoNFe,
      _RelCustosEntrega.ChaveAcessoNfe,
      _RelCustosEntrega.Motorista,
      _RelCustosEntrega.DataEmissaoDocFrete,
      _RelCustosEntrega.ChaveAcessoDocFrete,
      _RelCustosEntrega.CTENum,
      _RelCustosEntrega.NFSDanfeNum,
      _RelCustosEntrega.ValorFreteBruto,
      @ObjectModel.foreignKey.association: '_UGOrigem'
      _RelCustosEntrega.UGOrigem,
      _RelCustosEntrega.UFOrigem,
      _RelCustosEntrega.CidadeOrigem,
      _RelCustosEntrega.DataSaidaPlanejada,
      _RelCustosEntrega.DataSaidaReal,
      @ObjectModel.foreignKey.association: '_UGDestino'
      _RelCustosEntrega.UGDestino,
      _RelCustosEntrega.UFDestino,
      _RelCustosEntrega.CidadeDestino,
      _RelCustosEntrega.DataChegadaPlanejada,
      _RelCustosEntrega.DataChegadaReal,
      _RelCustosEntrega.BloqueioPlanejamento,
      _RelCustosEntrega.BloqueioExecucao,
      concat( cast( _RelCustosEntrega.UtilizacaoMaximaOF as abap.char( 90 ) ) , '%')                                   as UtilizacaoMaximaOF,
      _RelCustosEntrega.CondicaoExpedicao,
      _RelCustosEntrega.DescCondicaoExpedicao,
      _RelCustosEntrega.CodigoLocalTransporte,
      _RelCustosEntrega.DescLocalTransporte,
      _RelCustosEntrega.CodigoTransportadora,
      _RelCustosEntrega.NomeTransportadora,
      _RelCustosEntrega.NomeProduto,
      _RelCustosEntrega.ProductHierarchy5,
      _RelCustosEntrega.TipoExpedicao                                                                                  as TipoExpedicao,
      _RelCustosEntrega.DescTipoExpedicao                                                                              as DescTipoExpedicao,
      _FamiliaProdutoNivel1.vtext                                                                                      as FamiliaProdutosNivel1,
      _RelCustosEntrega.CodigoGrupoMercadorias,
      _RelCustosEntrega.CodigoProduto,
      _RelCustosEntrega.ProductHierarchy10,
      _FamiliaProdutoNivel2.vtext                                                                                      as FamiliaProdutosNivel2,
      _RelCustosEntrega.ProductHierarchy                                                                               as CodigoHierarquiaProduto,
      _FamiliaProdutoNivel3.vtext                                                                                      as FamiliaProdutosNivel3,
      _RelCustosEntrega.ModificadoPor,
      _RelCustosEntrega.ProductHierarchy,
      _RelCustosEntrega.DescGrupoMercadoria,

      concat_with_space(concat(_RelCustosEntrega.CodigoTipoTransporte, ' -'), _RelCustosEntrega.DescTipoTransporte, 1) as TipoTransporte,

      _RelCustosEntrega.DescTipoTransporte,

      _RelCustosEntrega.CodigoTipoTransporte                                                                           as TipoTransporte2,

      _RelCustosEntrega.NumeroFaturaGKO,

      _RelCustosEntrega.TotalItensNF,

      _RelCustosEntrega.PesoBruto,
      _RelCustosEntrega.PesoBrutoUnidade,
      _RelCustosEntrega.PesoLiquido,
      _RelCustosEntrega.PesoLiquidoUnidade,

      _RelCustosEntrega.CodigoCliente,
      _RelCustosEntrega.NomeCliente,
      _RelCustosEntrega.NumeroRemessa,
      _RelCustosEntrega.TipoRemessa,
      _RelCustosEntrega.DescTipoRemessa,

      _RelCustosEntrega.StatusOrdemFreteCicloVida,
      _RelCustosEntrega.DescStatusOrdemFreteCicloVida,

      _RelCustosEntrega.StatusOrdemFretePlanejamento,
      _RelCustosEntrega.DescStatusOrdemFretePlan,

      _RelCustosEntrega.StatusOrdemFreteExecucao,
      _RelCustosEntrega.DescStatusOrdemFreteExecucao,

      _RelCustosEntrega.NumeroCargaSAGA,
      _RelCustosEntrega.TipoOrdemFrete,
      _RelCustosEntrega.DescTipoOrdemFrete,
      _RelCustosEntrega.UnidadeFrete,
      _RelCustosEntrega.CustoEntregaLiquidoRS,
      _RelCustosEntrega.Cofins,
      _RelCustosEntrega.Pis,
      //    _RelCustosEntrega.PesoBrutoEcom,
      //    _RelCustosEntrega.VolumeCubadoEcom,
      fltp_to_dec( _RelCustosEntrega.PesoBrutoEcom as abap.dec(10,2) )                                                 as PesoBrutoEcom,
      fltp_to_dec( _RelCustosEntrega.VolumeCubadoEcom as abap.dec(10,2) )                                              as VolumeCubadoEcom,
      _RelCustosEntrega.ValorICMS,
      _RelCustosEntrega.ValorISS,
      _RelCustosEntrega.ValorCreditoICMS,
      _RelCustosEntrega.ValorNFITEM,

      //Association
      _UGOrigem,
      _UGDestino
}
group by
  _RelCustosEntrega.OrdemId,
  _RelCustosEntrega.OrdemFreteNum,
  _RelCustosEntrega.DataCriacaoOF,
  _RelCustosEntrega.CriadoPorOF,
  _RelCustosEntrega.Placa,
  _RelCustosEntrega.GrupoVeiculo,
  _RelCustosEntrega.TipoVeiculo,
  _RelCustosEntrega.DocNum,
  _RelCustosEntrega.NotaFiscalNum,
  _RelCustosEntrega.DataEmissaoNFe,
  _RelCustosEntrega.ChaveAcessoNfe,
  _RelCustosEntrega.Motorista,
  _RelCustosEntrega.DataEmissaoDocFrete,
  _RelCustosEntrega.ChaveAcessoDocFrete,
  _RelCustosEntrega.CTENum,
  _RelCustosEntrega.NFSDanfeNum,
  _RelCustosEntrega.ValorFreteBruto,
  _RelCustosEntrega.UGOrigem,
  _RelCustosEntrega.UFOrigem,
  _RelCustosEntrega.CidadeOrigem,
  _RelCustosEntrega.DataSaidaPlanejada,
  _RelCustosEntrega.DataSaidaReal,
  _RelCustosEntrega.UGDestino,
  _RelCustosEntrega.UFDestino,
  _RelCustosEntrega.CidadeDestino,
  _RelCustosEntrega.DataChegadaPlanejada,
  _RelCustosEntrega.DataChegadaReal,
  _RelCustosEntrega.BloqueioPlanejamento,
  _RelCustosEntrega.BloqueioExecucao,
  _RelCustosEntrega.UtilizacaoMaximaOF,
  _RelCustosEntrega.CondicaoExpedicao,
  _RelCustosEntrega.DescCondicaoExpedicao,
  _RelCustosEntrega.CodigoLocalTransporte,
  _RelCustosEntrega.DescLocalTransporte,
  _RelCustosEntrega.CodigoTransportadora,
  _RelCustosEntrega.NomeTransportadora,
  _RelCustosEntrega.NomeProduto,
  _RelCustosEntrega.ProductHierarchy5,
  _RelCustosEntrega.TipoExpedicao,
  _RelCustosEntrega.DescTipoExpedicao,
  _FamiliaProdutoNivel1.vtext,
  _RelCustosEntrega.CodigoGrupoMercadorias,
  _RelCustosEntrega.CodigoProduto,
  _RelCustosEntrega.ProductHierarchy10,
  _FamiliaProdutoNivel2.vtext,
  _RelCustosEntrega.ProductHierarchy,
  _FamiliaProdutoNivel3.vtext,
  _RelCustosEntrega.ModificadoPor,
  _RelCustosEntrega.ProductHierarchy,
  _RelCustosEntrega.DescGrupoMercadoria,
  _RelCustosEntrega.CodigoTipoTransporte,
  _RelCustosEntrega.DescTipoTransporte,
  _RelCustosEntrega.NumeroFaturaGKO,
  _RelCustosEntrega.TotalItensNF,
  _RelCustosEntrega.PesoBruto,
  _RelCustosEntrega.PesoBrutoUnidade,
  _RelCustosEntrega.PesoLiquido,
  _RelCustosEntrega.PesoLiquidoUnidade,
  _RelCustosEntrega.CodigoCliente,
  _RelCustosEntrega.NomeCliente,
  _RelCustosEntrega.NumeroRemessa,
  _RelCustosEntrega.TipoRemessa,
  _RelCustosEntrega.DescTipoRemessa,
  _RelCustosEntrega.StatusOrdemFreteCicloVida,
  _RelCustosEntrega.StatusOrdemFretePlanejamento,
  _RelCustosEntrega.DescStatusOrdemFretePlan,
  _RelCustosEntrega.StatusOrdemFreteExecucao,
  _RelCustosEntrega.DescStatusOrdemFreteExecucao,
  _RelCustosEntrega.DescStatusOrdemFreteCicloVida,
  _RelCustosEntrega.NumeroCargaSAGA,
  _RelCustosEntrega.TipoOrdemFrete,
  _RelCustosEntrega.DescTipoOrdemFrete,
  _RelCustosEntrega.UnidadeFrete,
  _RelCustosEntrega.CustoEntregaLiquidoRS,
  _RelCustosEntrega.Cofins,
  _RelCustosEntrega.Pis,
  _RelCustosEntrega.PesoBrutoEcom,
  _RelCustosEntrega.VolumeCubadoEcom,
  _RelCustosEntrega.ValorICMS,
  _RelCustosEntrega.ValorISS,
  _RelCustosEntrega.ValorCreditoICMS,
  _RelCustosEntrega.ValorNFITEM
