class ZCLTM_WLF_DOCUMENT_EXT definition
  public
  final
  create public .

public section.

  interfaces IF_BADI_INTERFACE .
  interfaces IF_WLF_DOCUMENT_EXT .
protected section.
private section.
ENDCLASS.



CLASS ZCLTM_WLF_DOCUMENT_EXT IMPLEMENTATION.


  METHOD if_wlf_document_ext~check_copa_relevant.
    c_re_determination_relevant = 'X'.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~ADD_ITEMS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~ADJUST_DOCUMENT_STATUS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~ADOPT_PRICING_COMPLETE_DATA.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~ADOPT_PRICING_DATA.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~ADOPT_PRICING_VALUES.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~ASSIGN_NEW_LIST_ITEM_NUMBER.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~AT_COPA_GET_PAOBJNR.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~AT_MATERIAL_READ.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CANCEL_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CANCEL_CONSISTENCY_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_AFTER_PREPARATION.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_AFTER_PRICING_COMPLETE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_AFTER_PRICING_COPY.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_AFTER_READ.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_AFTER_READ_PREFETCH.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_AT_UPDATE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_BEFORE_PRICING_COPY.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_BEFORE_UPDATE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_DOC_CHECK_PARAMETERS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_FIELD_STATUS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_FIELD_STATUS_TC.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_HEADER_DATA.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_ITEM_DATA.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_ITEM_DATA_BEFOR_PRICING.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_KSCHL_EXCLUDED_KSTEU_G.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_PRICING_HEADER.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_PRICING_ITEM.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_PRICING_TYPE_DOC_CHANGE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_PRICING_TYPE_FI.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHANGE_PROFIT_SIM_PARAMETERS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_BEFORE_UPDATE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_CASH_MNGT_RELEVANT.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_HEADER_DATA.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_HEADER_DATA_LIST_INPUT.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_HEADER_FOR_NEW_PRICING.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_ITEM_DATA.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_KSCHL_RELEVANCY.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_LFART_FOR_WRART.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_NEW_PRICING_ALLOWED_DOC.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_NEW_PRICING_ALLOWED_ITEM.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_ORG_DATA.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_PAYM_RECEIVER.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_V_TMFK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CHECK_V_TMZR.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CLEAN_UP.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~CLOSE_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~DATALOSS_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~DATA_ADOPTION_FOLLOW_DOC_ITEM.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~DATA_ADOPTION_INV_COLLECTION.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~DATA_ADOPTION_PAYMENT_LIST.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~DATA_ADOPTION_PAYM_LIST_ITEM.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~DATA_ADOPTION_REMU_LIST.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~DATA_ADOPTION_REMU_LIST_ITEM.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~FI_DOCUMENT_CHANGE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~FI_DOCUMENT_CHANGE_PARAMETERS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~FI_DOCUMENT_CREATE_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~HANDLE_KUNRG_NOT_IN_BUKRS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~HANDLE_UNKNOWN_WFKME.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~INVOICE_COLL_CREATE_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~INVOICE_LIST_CREATE_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~IS_TAXCODE_ALLOWED.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~NUMBER_CHANGE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~PAYMENT_LIST_CREATE_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~PROFIT_SIMULATION.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~REFRESH.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~REOPEN_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SALES_AREA_DETERMINE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SAVE_CHECK.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_ASSORTMENT_INACTIVE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_FI_DOCUMENT_SPLITT.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_HISTORY_WRITE_STATUS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_ITEM_MAX.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_ITEM_TEXT_IN_NODES.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_KONV_CHANGE_BAPI.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_PRICING_COMPLETE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_PRICING_TRANSACTION_TYPE.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SET_REFERENCE_FIELDS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SORT_DOCUMENTS_REPORT_PROCESS.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SPLIT_UPDATE_CALL.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~SWU_OBJECT_PUBLISH.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~TEXT_CHANGE_ALLOWED.
    RETURN.
  ENDMETHOD.


  METHOD IF_WLF_DOCUMENT_EXT~VENDOR_CUSTOMER_CHECK.
    RETURN.
  ENDMETHOD.


  method IF_WLF_DOCUMENT_EXT~AT_HEADER_CREATE_API.
      RETURN.
  endmethod.
ENDCLASS.
