*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVTM_TPVEI_SAGA.................................*
FORM GET_DATA_ZVTM_TPVEI_SAGA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTTM_TPVEI_SAGA WHERE
(VIM_WHERETAB) .
    CLEAR ZVTM_TPVEI_SAGA .
ZVTM_TPVEI_SAGA-MANDT =
ZTTM_TPVEI_SAGA-MANDT .
ZVTM_TPVEI_SAGA-TURES_TCO_SAGA =
ZTTM_TPVEI_SAGA-TURES_TCO_SAGA .
ZVTM_TPVEI_SAGA-TURES_TCO =
ZTTM_TPVEI_SAGA-TURES_TCO .
<VIM_TOTAL_STRUC> = ZVTM_TPVEI_SAGA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVTM_TPVEI_SAGA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVTM_TPVEI_SAGA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVTM_TPVEI_SAGA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTTM_TPVEI_SAGA WHERE
  TURES_TCO_SAGA = ZVTM_TPVEI_SAGA-TURES_TCO_SAGA AND
  TURES_TCO = ZVTM_TPVEI_SAGA-TURES_TCO .
    IF SY-SUBRC = 0.
    DELETE ZTTM_TPVEI_SAGA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTTM_TPVEI_SAGA WHERE
  TURES_TCO_SAGA = ZVTM_TPVEI_SAGA-TURES_TCO_SAGA AND
  TURES_TCO = ZVTM_TPVEI_SAGA-TURES_TCO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTTM_TPVEI_SAGA.
    ENDIF.
ZTTM_TPVEI_SAGA-MANDT =
ZVTM_TPVEI_SAGA-MANDT .
ZTTM_TPVEI_SAGA-TURES_TCO_SAGA =
ZVTM_TPVEI_SAGA-TURES_TCO_SAGA .
ZTTM_TPVEI_SAGA-TURES_TCO =
ZVTM_TPVEI_SAGA-TURES_TCO .
    IF SY-SUBRC = 0.
    UPDATE ZTTM_TPVEI_SAGA ##WARN_OK.
    ELSE.
    INSERT ZTTM_TPVEI_SAGA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVTM_TPVEI_SAGA-UPD_FLAG,
STATUS_ZVTM_TPVEI_SAGA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVTM_TPVEI_SAGA.
  SELECT SINGLE * FROM ZTTM_TPVEI_SAGA WHERE
TURES_TCO_SAGA = ZVTM_TPVEI_SAGA-TURES_TCO_SAGA AND
TURES_TCO = ZVTM_TPVEI_SAGA-TURES_TCO .
ZVTM_TPVEI_SAGA-MANDT =
ZTTM_TPVEI_SAGA-MANDT .
ZVTM_TPVEI_SAGA-TURES_TCO_SAGA =
ZTTM_TPVEI_SAGA-TURES_TCO_SAGA .
ZVTM_TPVEI_SAGA-TURES_TCO =
ZTTM_TPVEI_SAGA-TURES_TCO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVTM_TPVEI_SAGA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVTM_TPVEI_SAGA-TURES_TCO_SAGA TO
ZTTM_TPVEI_SAGA-TURES_TCO_SAGA .
MOVE ZVTM_TPVEI_SAGA-TURES_TCO TO
ZTTM_TPVEI_SAGA-TURES_TCO .
MOVE ZVTM_TPVEI_SAGA-MANDT TO
ZTTM_TPVEI_SAGA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTTM_TPVEI_SAGA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTTM_TPVEI_SAGA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTTM_TPVEI_SAGA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
